# Generated by Django 3.2.11 on 2022-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('barrio_vereda', models.CharField(max_length=200)),
                ('subcuenca', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('operador', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('red', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('datos_enviados', models.IntegerField()),
                ('topicos_enviados', models.IntegerField()),
                ('datos_recuperados', models.IntegerField()),
                ('ultima_actualizacion', models.DateTimeField()),
            ],
        ),
    ]
